# yaml-language-server: $schema=https://raw.githubusercontent.com/grafana/cog/main/schemas/unit.json

inputs:
  - cue:
      entrypoint: '%__config_dir%'

builder_transformations:
  - '%__config_dir%/common.builder.transforms.yaml'
