name: Java Release
on:
  push:
    tags: ["v*"]

env:
  JAVA_VERSION: '17'

jobs:
  release:
    name: Build and release
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    defaults:
      run:
        shell: bash
        working-directory: ./java

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Uses Java SDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 #v5.2.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'
          check-latest: true

      - name: Java setup gradle
        uses: gradle/actions/setup-gradle@f29f5a9d7b09a7c6b29859002d29d24e1674c884 #v5.0.1
        with:
          gradle-version: '9.3'
          cache-disabled: true

      - name: Get secrets
        uses: grafana/shared-workflows/actions/get-vault-secrets@75804962c1ba608148988c1e2dc35fbb0ee21746
        with:
          repo_secrets: |
            MAVEN_USERNAME=secrets:maven_username
            MAVEN_PASSWORD=secrets:maven_password
            GPG_PASSPHRASE=gpg:passphrase
            GPG_PUBLIC_KEY=gpg:public-key
            GPG_PRIVATE_KEY=gpg:private-key

      - name: Publish package ðŸ“¦
        env:
          MAVEN_USERNAME: ${{ env.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ env.MAVEN_PASSWORD }}
          GPG_PASSPHRASE: ${{ env.GPG_PASSPHRASE }}
          GPG_PUBLIC_KEY: ${{ env.GPG_PUBLIC_KEY }}
          GPG_PRIVATE_KEY: ${{ env.GPG_PRIVATE_KEY }}
        run: gradle publishToSonatype closeAndReleaseSonatypeStagingRepository
